#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
cont=0
while [ $cont -lt 10 ];
do
  if [ $cont -eq 9 ]
  then
    echo "Hi"
  fi
  else
  echo "Best School"
  ((cont++))
done
