#!/usr/bin/env bash
#Bash script displays Best School 10 times except for 4 and 8"
cont=0
while [ $cont -lt 10 ];
do
    if [ $cont -eq 4 ]
    then
echo "bad luck"
    elif [ $cont -eq 8 ]
    then
echo "good luck"
    else
echo "Holberton School"
    fi
    ((cont++))
done
