#!/usr/bin/env bash
#Bash Script that prints numbers 1 to 20 with special messages for 4, 9, and 17.
Counter=1
while [ "$Counter" -le 20 ];
    do
    echo "$Counter"
    case "$Counter" in
4)
    echo "bad luck from China"
    ;;
9)
    echo "bad luck from Japan"
    ;;
17)
    echo "bad luck from Italy"
    ;;
    esac
    let Counter=Counter+1
done
