#!/usr/bin/env bash
#Bash script that displays hours and minutes
hour=0
while [ $hour -le 12 ];
do
    echo "Hour: $hour"
    minutes=1
    while [ $minutes -le 59 ];
    do
echo  $minutes
let minutes=minutes+1
    done
    ((hour++))
done
